### ISSUE TITLE
Alex's next post 06/03

### ISSUE THREAD

**Issue by beatrizcp87** [Helabs/blog#357]
Hey Alex, you have a new post date.
Please, call me If you need any help.

**Comment by alexbrahastoll** [comment]
Hi, Bia =)

I won't be able to write a post until this date. I don't have much time at the moment because some side projects are using almost all my free time! To be honest, right now I don't feel comfortable defining a specific date to my next post.

But hey, it's not all bad news: I promise to write a post about the usage of UUIDs in Ruby until the end of March (much likely towards the very end of this month).

Cheers.
